import { test } from 'node:test';import assert from 'node:assert/strict';
import { runCheck, linkedDocuments, checkResource } from './check-governance.mjs';
const page='https://www.fda.gov/example',pdf='https://www.fda.gov/media/123/download';
const entry={id:'test',source:page,primaryDocuments:[{url:pdf}]};
const html='<main>'+ 'Evidence '.repeat(30) + `<a href="${pdf}">Guidance</a></main>`;
function fetcher(pageBody,docBody,status=200){return async url=>new Response(url===page?pageBody:docBody,{status,headers:{'content-type':url===page?'text/html':'application/pdf'}});}
const bytes='%PDF-'+ 'original '.repeat(30);
test('document changes detected when landing page unchanged; baseline remains unaccepted',async()=>{const first=await runCheck([entry],{},fetcher(html,bytes));const next=await runCheck([entry],first.next,fetcher(html,bytes+'changed'));assert.equal(next.report.results[0].outcome,'unchanged');assert.deepEqual(next.report.signals.map(s=>s.type),['underlying-document-change']);assert.equal(next.next[next.report.results[1].key].hash,first.next[first.report.results[1].key].hash);});
test('page change and new document link remain separate review signals',async()=>{const first=await runCheck([entry],{},fetcher(html,bytes));const next=await runCheck([entry],first.next,fetcher(html+'<a href="https://www.fda.gov/media/456/download">New</a>',bytes));assert.deepEqual(next.report.signals.map(s=>s.type),['landing-page-change','newly-discovered-document']);assert.equal(next.report.results[1].outcome,'unchanged');});
test('fetch failures retain previous baselines and do not change entries',async()=>{const before=JSON.stringify(entry);const baseline={test:{hash:'previous'}};const next=await runCheck([entry],baseline,fetcher(html,bytes,503));assert.deepEqual(next.next,baseline);assert.ok(next.report.results.every(r=>r.outcome==='unavailable'));assert.equal(JSON.stringify(entry),before);});
test('reject challenge pages disguised as PDFs; do not count as verification',async()=>{const r=await checkResource({key:'x',url:pdf,kind:'primary-document',entryId:'x'},{},async()=>new Response('<html>captcha</html>',{headers:{'content-type':'application/pdf'}}));assert.equal(r.outcome,'unavailable');});
test('discovery excludes nonofficial documents and images',()=>{assert.equal(linkedDocuments('<a href="https://evil.example/test.pdf">X</a><a href="/image.png">Y</a>',page).length,0);});
